# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-15 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
