# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
